In [1]:
import numpy as np

**1. Create 4x4 array with all values  set to True**

In [2]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**2. Create 4x4 array with all values set to False**

In [3]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**3. Create 4x4 array with diagonal values set to True and non diagonal False**

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**4. Create 4x4 array with diagonal values set to False and non diagonal True**

In [17]:
a = np.identity(4)

In [19]:
b= np.ones((4,4))

In [25]:
matrix = b - a
print(matrix)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
