In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
a = np.array([2,3,4])

In [9]:
a.ndim

1

In [10]:
a=np.array([[2,5,5],[66,7,2]])

In [11]:
a.ndim

2

In [16]:
a= np.array([[[1,2,3]],[[5,6,4]]])

In [17]:
a.ndim

3

In [18]:
#Create 2D array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# 3D(block,rows,columns) array
np.ones((3,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
b = np.ones((5,2,3))

In [23]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
b.ndim

3